listen: 0.0.0.0:443

acme:
  domains:
    - vps.css520.dpdns.org
  email: cjw9831@gmail.com
  type: dns
  dns:
    name: cloudflare
    config:
      cloudflare_api_token: cfut_Udpmq04s9x0uPEyyuSTpvwAJwN9h1l8SNRsHeTqJ1a63ffde

auth:
  type: password
  password: c83d79093d92a578a3dd6970f2401136ae27dc63862f9cb723b0f0172e556a23

outbounds:
  - name: direct
    type: direct

  - name: warp
    type: socks5
    socks5:
      addr: 127.0.0.1:40000

acl:
  inline:
    - warp(suffix:gemini.google.com)
    - warp(suffix:generativelanguage.googleapis.com)
    - warp(suffix:ai.google.dev)
    - warp(suffix:googleapis.com)
    - warp(suffix:googleusercontent.com)
    - warp(suffix:gstatic.com)
    - warp(suffix:google.com)
    - direct(all)

masquerade:
  type: proxy
  proxy:
    url: https://news.ycombinator.com/
    rewriteHost: true
